export const categoriesByType = {
  expense: [
    "Food",
    "Groceries",
    "Rent",
    "EMI",
    "Utilities",
    "Electricity",
    "Water",
    "Internet",
    "Fuel",
    "Travel",
    "Transport",
    "Shopping",
    "Health",
    "Medical",
    "Education",
    "Entertainment",
    "Subscription",
    "Insurance",
    "Gift",
    "Family",
    "Loan",
    "Borrow",
    "Other",
  ],
  income: [
    "Salary",
    "Freelance",
    "Business",
    "Bonus",
    "Interest",
    "Refund",
    "Gift",
    "Loan Return",
    "Borrow Received",
    "Other",
  ],
  invest: [
    "Mutual Fund",
    "Stock",
    "Gold",
    "Crypto",
    "FD",
    "PPF",
    "NPS",
    "SIP",
    "Real Estate",
    "Other",
  ],
};

export const categoryAliasesByType = {
  expense: {
    Food: [
      "idly",
      "dosa",
      "briyani",
      "biryani",
      "breakfast",
      "lunch",
      "dinner",
      "hotel",
      "restaurant",
    ],
    Groceries: [
      "atta",
      "rice",
      "dal",
      "oil",
      "soap",
      "shampoo",
      "toothpaste",
      "vegetable",
      "milk",
    ],
    Fuel: ["petrol", "diesel", "gas", "cng"],
    Utilities: ["bill", "recharge", "electricity", "water", "internet"],
    Medical: ["medicine", "tablet", "doctor", "clinic", "hospital"],
    Transport: ["auto", "cab", "uber", "ola", "bus", "train", "metro"],
  },
  income: {
    Salary: ["pay", "salary", "wage"],
    Freelance: ["client", "project", "gig"],
    Interest: ["interest", "bank interest"],
    Refund: ["refund", "cashback"],
  },
  invest: {
    "Mutual Fund": ["mf", "fund", "sip"],
    Stock: ["share", "equity", "stock"],
    Gold: ["gold", "jewelry", "bullion"],
    Crypto: ["bitcoin", "btc", "eth", "crypto"],
  },
};
